### ISSUE TITLE
Require to have org.freedesktop.Platform.ffmpeg-full

### ISSUE THREAD

**Issue by Rrauros** [flathub/net.waterfox.waterfox#11]
Right now waterfox package relies on org.freedesktop.Platform.openh264 like firefox does. But I'm currently having stutters problem with openh264 and ffmpeg package is more performant in general. It would be nice to require ffmpeg package by default. 

When installing org.freedesktop.Platform.ffmpeg-full seperetely waterfox still relies and looks for openh264 while firefox flatpak package when finds ffmpeg in the system it uses that rather than openh264. If waterfox also can do the same it would be great.

**Comment by FloridaMan7588** [comment]
I will look into this, although I would like to shy away from having extra dependencies. Although I suppose with the nature of flatpaks, it might not be a big deal.

**Comment by FloridaMan7588** [comment]
I have realized before that the browser wants h264 to be installed, but it doesn't seem to be hard-coded in the manifest. I think the openh264 requirement is a Flathub thing. I will still look into adding the ffmpeg runtime extension.

**Comment by FloridaMan7588** [comment]
Fixed in #13
