### ISSUE TITLE
Updating Flatpak Version

### ISSUE THREAD

**Issue by sorayastar** [flathub/net.waterfox.waterfox#15]
Hello, apologies for this but I'm not sure where/how else to ask.

Waterfox is telling me there is an update available, but my package manager cannot find it, and it takes me to flathub for the download.

Currently running KDE neon 5.27, KDE Plasma v5.27.7, KDE Frameworks v5.108.0

Attempting to update from G5.1.9 to G5.1.10 via the Discover store.

Thanks for any and all help.

**Comment by FloridaMan7588** [comment]
Sorry, I have to approve the updates for them to be published on Flathub. I've been on holiday so I haven't had a chance to push the new version. It will be available in the next few hours. Again so sorry about that!
