### ISSUE TITLE
Video abnormal stuttering and shake in Bilibili

### ISSUE THREAD

**Issue by traditionalgithub** [flathub/net.waterfox.waterfox#29]
The flatpak version of Waterfox experiences abnormal stuttering and frame retraction in some of the video in Bilibili, for example https://www.bilibili.com/video/BV1P14y1z7KY/?vd_source=e486cbdb8f3dfdbdc8b458983aaf0036, as this skit shows:
https://github.com/flathub/net.waterfox.waterfox/assets/45969856/4c4b187c-2021-40af-9c40-6b6247f615c1
This screen cap is shot in with Waterfox running trouble shooting mode.

I found this situatioin only in Bilibili. The Waterfox version is G6.0.5 (64bit), the OS running it is OpenSuse Tumbleweed, the VGA card is nVidia GP106M [GeForce GTX 1060 Mobile],  running proprietary driver.

**Comment by FloridaMan7588** [comment]
Fixed in #13
